name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        env:
          JIRA_SECRET_KEY: ${{ secrets.JIRA_SECRET_KEY }}
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t kcvijay121/jiraApi-automation:latest

      - name: Push Docker image
        run: docker push kcvijay121/jiraApi-automation:latest

