name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        env:
          JIRA_SECRET_KEY: ${{ secrets.JIRA_SECRET_KEY }}
        run: mvn -B package --file pom.xml